from flask import Flask, render_template, make_response, redirect, url_for
import datetime

app = Flask(__name__)


@app.route("/myhome", methods=["post", "get"])
def myhome():
    now = datetime.datetime.now()
    return render_template("home.html", curr_now=now)


@app.route("/method")
def method():
    return render_template("method.html")


@app.route("/about")
def about():
    headers = {"Content-Type": "application/json"}
    return make_response("This response is generated by make_response", 201, headers)


@app.route("/base")
def base():
    return redirect(url_for("myhome"))


@app.route("/search")
def search():
    return redirect("http://www.google.com")


if __name__ == "__main__":
    app.run(debug=True)
